package ua.com.foxminded.university;

public enum TypeOfEntity {
    CAMPUS, CLASSROOM, FACULTIES, GROUP, LESSON, PERSON, POSITION, STUDENT, SUBJECT, TEACHER, SCHEDULE, DAILYSCHEDULE,
    MONTHLYSHCEDULE;
}
